### ISSUE TITLE
Proposal Core Ontology: belongsToVehicleComponents for static property relation not according to OWL

### ISSUE THREAD

**Issue by danielwilms** [w3c/vsso#8]
Thanks to the discussion today, we highlighted the `vsso:VehicleComponent` relation from the `vsso:StaticVehicleProperty`  to the `vsso:VehicleComponent`. It was correctly argued, that this is not owl compliant. This brings me to the discussion, whether this information is actually needed. 

The static properties define the vehicle itself and the connection to the component might just be overhead. There are two example queries (Q08, Q11), which would not be resolvable by dropping the relation.  So, one thing is how to keep the information and how to model it formally correct. The other question is, whether the information is actually needed.

Happy to hear your opinion. #5

**Comment by danielwilms** [comment]
Apart from the question, if the information is needed, modelling the property as an `ObjectProperty` was indeed wrong and let to some confusion. The reason for the property was, that the branches as individuals are providing more context to the static and dynamic vehicle properties. I still think, that this approach is valid and that `belongsToVehicleComponent` could be actually modelled through a `owl:AnnotationProperty`. We'll push the code and the model later today, so that you can see how it looks like. What do you think?

**Comment by rtroncy** [comment]
I don't understand the paragraph in https://github.com/w3c/vsso/issues/8#issue-804965847. What is `vsso:VehicleComponent`? Certainly  NOT a property as it is written. What is `vsso:StaticVehicleProperty`? None of those terms are defined in this [turtle file](https://github.com/w3c/vsso/blob/main/vsso.ttl).

What would be the definition of an hypothetical `vsso:belongsToVehicleComponent` property? A `owl:AnnotationProperty` conveys no semantics!

**Comment by danielwilms** [comment]
@rtroncy, it's about the core ontology proposal. Maybe I should keep the discussion in only one issue.

**Comment by jdacoello** [comment]
What @danielwilms is referring to is the following:

We made a [proposal for the core Vehicle Signal Specification Ontology (VSSo)](http://doi.org/10.13140/RG.2.2.14695.78240) as an approach to keep the ontology fully synchronized and aligned with the continuous evolution of the Vehicle Signal Specification (VSS).
The principal elements of the semantic model consist of:
* Classes: `Vehicle`, `VehicleComponent`, `DynamicVehicleProperty`
* Object properties: `hasDynamicVehicleProperty`, `partOf`
* Data properties: `hasStaticVehicleProperty` (i.e., all the fixed attributes of a vehicle, like VIN, model, brand, etc.)
* Annotation properties: `belongsToVehicleComponent`

With them, we can resemble the tree-like structure of VSS.
The issue corresponds to a recent observation about one of the properties proposed (i.e., `belongsToVehicleComponent`). The issue was that we wrongly connected a the data property `hasStaticVehicleProperty` with the class `VehicleComponent` using a the object property `belongsToVehicleComponent`. Such a connection was not compliant to OWL. Therefore, we changed `belongsToVehicleComponent` from being an object property to an annotation property. All the queries were tested with this adjustment and are working. Pull request was already made and demo repository should be updated soon.

Another option we tried and that could be also a valid solution with more semantics is to keep `belongsToVehicleComponent` as an object property and add the class `StaticVehicleProperty`. In this way, each fixed attribute of a vehicle defined in VSS would be mapped to a subclass of `StaticVehicleProperty`.

**Comment by felix-loesch** [comment]
A solution proposal to make VSSo OWL compliant that we Felix, Anees (Bosch) discussed with @danielwilms is as follows:

- Classes: _Vehicle_, _VehicleComponent_, _StaticVehicleProperty_, _DynamicVehicleProperty_
- Object Properties: _belongsToVehicleComponent_ (domain=StaticVehicleProperty or DynamicVehicleProperty, range=VehicleComponent), _hasStaticVehicleProperty_ (domain=Vehicle, range=StaticVehicleProperty), _hasDynamicVehicleProperty_ (domain=Vehicle, range=DynamicVehicleProperty)

This approachs makes VSSo OWL compliant as object properties, especially _belongsToVehicleComponent_ is used according to OWL standard, i.e., relating the two classes _StaticVehicleProperty_ or _DynamicVehicleProperty_ and _VehicleComponent_

**Comment by danielwilms** [comment]
Included in current proposal
